# Generated by Django 2.2.6 on 2020-03-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
