# Generated by Django 2.2.6 on 2020-03-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customeUser',
        ),
    ]
